// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type NewsletterArticle struct {
	ID           int64  `json:"id"`
	Url          string `json:"url"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Newsletter   string `json:"newsletter"`
	EmailSubject string `json:"email_subject"`
	EmailDate    string `json:"email_date"`
	EmailFile    string `json:"email_file"`
	CreatedAt    string `json:"created_at"`
}

type Rsvp struct {
	ID              int64     `json:"id"`
	MeetingNumber   int64     `json:"meeting_number"`
	Name            string    `json:"name"`
	Email           string    `json:"email"`
	NewsletterOptIn bool      `json:"newsletter_opt_in"`
	Responses       string    `json:"responses"`
	CreatedAt       time.Time `json:"created_at"`
}

type SlackLink struct {
	ID          int64     `json:"id"`
	Url         string    `json:"url"`
	ChannelID   string    `json:"channel_id"`
	ChannelName string    `json:"channel_name"`
	UserID      string    `json:"user_id"`
	UserName    string    `json:"user_name"`
	MessageTs   string    `json:"message_ts"`
	MessageText string    `json:"message_text"`
	CreatedAt   time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
