// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rsvps.sql

package dbgen

import (
	"context"
)

const rSVPExists = `-- name: RSVPExists :one
SELECT COUNT(*) FROM rsvps WHERE meeting_number = ? AND email = ?
`

type RSVPExistsParams struct {
	MeetingNumber int64  `json:"meeting_number"`
	Email         string `json:"email"`
}

func (q *Queries) RSVPExists(ctx context.Context, arg RSVPExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, rSVPExists, arg.MeetingNumber, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const rSVPsByMeeting = `-- name: RSVPsByMeeting :many
SELECT id, meeting_number, name, email, newsletter_opt_in, responses, created_at
FROM rsvps
WHERE meeting_number = ?
ORDER BY created_at ASC
`

func (q *Queries) RSVPsByMeeting(ctx context.Context, meetingNumber int64) ([]Rsvp, error) {
	rows, err := q.db.QueryContext(ctx, rSVPsByMeeting, meetingNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rsvp{}
	for rows.Next() {
		var i Rsvp
		if err := rows.Scan(
			&i.ID,
			&i.MeetingNumber,
			&i.Name,
			&i.Email,
			&i.NewsletterOptIn,
			&i.Responses,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRSVP = `-- name: UpsertRSVP :exec
INSERT INTO rsvps (meeting_number, name, email, newsletter_opt_in, responses)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(meeting_number, email) DO UPDATE SET
    name = excluded.name,
    newsletter_opt_in = excluded.newsletter_opt_in,
    responses = excluded.responses
`

type UpsertRSVPParams struct {
	MeetingNumber   int64  `json:"meeting_number"`
	Name            string `json:"name"`
	Email           string `json:"email"`
	NewsletterOptIn bool   `json:"newsletter_opt_in"`
	Responses       string `json:"responses"`
}

func (q *Queries) UpsertRSVP(ctx context.Context, arg UpsertRSVPParams) error {
	_, err := q.db.ExecContext(ctx, upsertRSVP,
		arg.MeetingNumber,
		arg.Name,
		arg.Email,
		arg.NewsletterOptIn,
		arg.Responses,
	)
	return err
}
