// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_links.sql

package dbgen

import (
	"context"
	"time"
)

const insertSlackLink = `-- name: InsertSlackLink :exec
INSERT OR IGNORE INTO slack_links (
    url, channel_id, channel_name, user_id, user_name, message_ts, message_text
)
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type InsertSlackLinkParams struct {
	Url         string `json:"url"`
	ChannelID   string `json:"channel_id"`
	ChannelName string `json:"channel_name"`
	UserID      string `json:"user_id"`
	UserName    string `json:"user_name"`
	MessageTs   string `json:"message_ts"`
	MessageText string `json:"message_text"`
}

func (q *Queries) InsertSlackLink(ctx context.Context, arg InsertSlackLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertSlackLink,
		arg.Url,
		arg.ChannelID,
		arg.ChannelName,
		arg.UserID,
		arg.UserName,
		arg.MessageTs,
		arg.MessageText,
	)
	return err
}

const slackLinkCount = `-- name: SlackLinkCount :one
SELECT
    COUNT(*)
FROM
    slack_links
WHERE
    created_at >= ?
`

func (q *Queries) SlackLinkCount(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, slackLinkCount, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const slackLinksSince = `-- name: SlackLinksSince :many
SELECT
    id, url, channel_id, channel_name, user_id, user_name, message_ts, message_text, created_at
FROM
    slack_links
WHERE
    created_at >= ?
ORDER BY
    created_at DESC
`

func (q *Queries) SlackLinksSince(ctx context.Context, createdAt time.Time) ([]SlackLink, error) {
	rows, err := q.db.QueryContext(ctx, slackLinksSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackLink{}
	for rows.Next() {
		var i SlackLink
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ChannelID,
			&i.ChannelName,
			&i.UserID,
			&i.UserName,
			&i.MessageTs,
			&i.MessageText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
